import { BooleanStringType } from "@generalTypes/general";

export type JobInventoryType = {
  additional_info: string;
  art_type: string;
  art_type_id: string;
  artist: string;
  artist_id: string;
  child_parent_count: string;
  clientinv: string;
  clientinv2: null;
  clientinv_display: string;
  clientref: string;
  current_packing_detail: string;
  current_packing_detail_id: string;
  edition: string;
  fromlocation: string;
  fromlocation_display: string;
  has_condition_check: BooleanStringType;
  has_condition_report: BooleanStringType;
  id: number;
  medium: string;
  medium_id: string;
  must_update: number;
  netsuite_image: null;
  packed_cubit_foot: string;
  packed_height: string;
  packed_length: string;
  packed_square_foot: string;
  packed_width: string;
  packing_details_display: string;
  parent: string;
  parent_url: string;
  plain_id_job: number;
  provenance: null;
  status: string | null;
  unpacked_cubit_foot: string;
  unpacked_height: string;
  unpacked_length: string;
  unpacked_square_foot: string;
  unpacked_width: string;
  url: string;
  weight: string;
  year: string;
};
